# docker-compose.yaml이라는 이름으로 만들면
# docker-compose command를 사용할 때 기본으로 사용.

version : "3.9"     # docker-compose의 스키마의 버젼

services:           # services 밑에 container의 정의를 적어서 사용
  flask_app:
    container_name: flaskContainer
    build:          # 이미지를 빌드하여 사용
      context: .
    volumes:
      - $PWD/src:/opt/app
    ports:
      - "9000:8000"
    networks:
      - practice_network
    depends_on:
      - mongo

  mongo:
    container_name: mongoContainer
    image: mongo
    volumes:
      - $PWD/mongodb_data:/data/db
    ports:
      - "27018:27017"
    networks:
      - practice_network

# service container 들이 사용하는 named volume 이나 network를 정의해줘야됨
# service "flask_app" refers to undefined network practice_network: invalid compose project
networks:
  practice_network:

